"use client";

import { useCallback, useEffect, useState } from "react";
import { CLASSIC_CARD_COUNTS, GALATASARAY_PLAYERS, type MemoryPlayer } from "@/lib/memory/galatasarayPlayers";
import { memoryCreateRoom, memoryFlipCard, memoryGetState, memoryJoinRoom, memoryStartRoom, memoryTick, type MemorySession, type MemoryState } from "@/lib/memory/multiplayerApi";

function shuffle<T>(items: T[]) { const out = [...items]; for (let i = out.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [out[i], out[j]] = [out[j], out[i]]; } return out; }
function time(seconds: number) { return `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${(seconds % 60).toString().padStart(2, "0")}`; }
function PlayerCard({ player, open, matched, onClick }: { player: MemoryPlayer; open: boolean; matched?: boolean; onClick?: () => void }) {
  const [failed, setFailed] = useState(false);
  return <button className={`classic-card ${open ? "is-open" : ""} ${matched ? "is-matched" : ""}`} onClick={onClick} disabled={matched} aria-label={open ? player.name : "Kapalı oyuncu kartı"}><span className="classic-card-inner"><span className="classic-card-front"><img src="/galatasaray-logo.png" alt="" /></span><span className="classic-card-back">{failed ? <span className="player-silhouette" aria-hidden="true">GS</span> : <img src={player.image} alt="" onError={() => setFailed(true)} />}<strong>{player.name}</strong></span></span></button>;
}

type SoloCard = { id: string; pairId: string; player: MemoryPlayer };
function SoloClassic({ onBack }: { onBack: () => void }) {
  const [count, setCount] = useState<number>(12); const [cards, setCards] = useState<SoloCard[]>([]); const [open, setOpen] = useState<string[]>([]); const [matched, setMatched] = useState<string[]>([]); const [moves, setMoves] = useState(0); const [wrong, setWrong] = useState(0); const [seconds, setSeconds] = useState(0); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false);
  useEffect(() => { if (!cards.length || done) return; const timer = window.setInterval(() => setSeconds((v) => v + 1), 1000); return () => window.clearInterval(timer); }, [cards.length, done]);
  const score = Math.max(0, matched.length * 100 + Math.max(0, 600 - seconds * 5) - wrong * 25);
  function start() { const selected = shuffle(GALATASARAY_PLAYERS).slice(0, count / 2); setCards(shuffle(selected.flatMap((player) => [{ id: `${player.id}-a`, pairId: player.id, player }, { id: `${player.id}-b`, pairId: player.id, player }]))); setOpen([]); setMatched([]); setMoves(0); setWrong(0); setSeconds(0); setDone(false); setBusy(false); }
  function click(card: SoloCard) { if (busy || open.includes(card.id) || matched.includes(card.pairId)) return; const next = [...open, card.id]; setOpen(next); if (next.length !== 2) return; setBusy(true); setMoves((v) => v + 1); const first = cards.find((item) => item.id === next[0]); const isMatch = first?.pairId === card.pairId; window.setTimeout(() => { if (isMatch) { const nextMatched = [...matched, card.pairId]; setMatched(nextMatched); if (nextMatched.length === count / 2) setDone(true); } else setWrong((v) => v + 1); setOpen([]); setBusy(false); }, isMatch ? 280 : 780); }
  return <section className="classic-panel"><div className="classic-subbar"><button onClick={onBack}>← Modlar</button><span>KLASİK · TEK OYUNCU</span></div>{!cards.length || done ? <div className="classic-setup">{done ? <><p className="memory-kicker">🏆 HAFIZA TAMAMLANDI</p><h2>{score} PUAN</h2><p>{time(seconds)} · {moves} hamle · {wrong} yanlış</p></> : <><h2>Kart sayısını seç</h2></>}<div className="memory-category-grid classic-counts">{CLASSIC_CARD_COUNTS.map((value) => <button key={value} className={count === value ? "selected" : ""} onClick={() => setCount(value)}>{value} kart<span>{value / 2} çift</span></button>)}</div><button className="memory-primary-button" onClick={start}>{done ? "YENİDEN OYNA" : "OYUNA BAŞLA"} →</button></div> : <><div className="memory-stats"><span><b>{time(seconds)}</b><small>Süre</small></span><span><b>{moves}</b><small>Hamle</small></span><span><b>{matched.length}/{count / 2}</b><small>Doğru</small></span><span><b>{wrong}</b><small>Yanlış</small></span></div><div className={`classic-grid classic-grid-${count}`}>{cards.map((card) => <PlayerCard key={card.id} player={card.player} open={open.includes(card.id) || matched.includes(card.pairId)} matched={matched.includes(card.pairId)} onClick={() => click(card)} />)}</div></>}</section>;
}

function MultiplayerClassic({ onBack }: { onBack: () => void }) {
  const [session, setSession] = useState<MemorySession | null>(() => { if (typeof window === "undefined") return null; try { const raw = window.localStorage.getItem("gs_memory_session"); return raw ? JSON.parse(raw) as MemorySession : null; } catch { return null; } }); const [state, setState] = useState<MemoryState | null>(null); const [name, setName] = useState(""); const [code, setCode] = useState(""); const [maxPlayers, setMaxPlayers] = useState(2); const [cardCount, setCardCount] = useState(12); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async (next: MemorySession | null = session) => { if (!next) return; try { const result = await memoryGetState(next); setState(result.state); setError(""); } catch { setError("Oda bağlantısı yenilenemedi."); } }, [session]);
  // Session restore intentionally hydrates the remote state after the client mounts.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (session) void refresh(session); }, [refresh, session]);
  useEffect(() => { if (!session) return; const timer = window.setInterval(() => { void refresh(session); if (state?.room.status === "playing") void memoryTick(session).catch(() => undefined); }, 700); return () => window.clearInterval(timer); }, [refresh, session, state?.room.status]);
  async function enter(next: Promise<{ room_id: string; player_id: string; token: string; code: string }>) { setBusy(true); setError(""); try { const c = await next; const s: MemorySession = { version: 1, roomId: c.room_id, playerId: c.player_id, token: c.token, code: c.code }; window.localStorage.setItem("gs_memory_session", JSON.stringify(s)); setSession(s); await refresh(s); } catch (e) { setError(e instanceof Error ? e.message : "Odaya bağlanılamadı."); } finally { setBusy(false); } }
  if (!session || !state) return <section className="classic-panel"><div className="classic-subbar"><button onClick={onBack}>← Modlar</button><span>KLASİK · ÇOK OYUNCULU</span></div><div className="classic-setup"><h2>Oda oluştur veya katıl</h2><input className="memory-input" value={name} onChange={(e) => setName(e.target.value)} placeholder="Oyuncu adın" maxLength={24} /><div className="memory-category-grid classic-counts"><button onClick={() => setMaxPlayers(2)} className={maxPlayers === 2 ? "selected" : ""}>2 oyuncu</button><button onClick={() => setMaxPlayers(4)} className={maxPlayers === 4 ? "selected" : ""}>4 oyuncu</button><button onClick={() => setMaxPlayers(6)} className={maxPlayers === 6 ? "selected" : ""}>6 oyuncu</button><button onClick={() => setMaxPlayers(8)} className={maxPlayers === 8 ? "selected" : ""}>8 oyuncu</button></div><div className="memory-category-grid classic-counts">{CLASSIC_CARD_COUNTS.map((value) => <button key={value} className={cardCount === value ? "selected" : ""} onClick={() => setCardCount(value)}>{value} kart</button>)}</div><button className="memory-primary-button" disabled={!name.trim() || busy} onClick={() => void enter(memoryCreateRoom(name, maxPlayers, cardCount))}>ODA OLUŞTUR</button><div className="memory-join-row"><input className="memory-input" value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="6 haneli kod" maxLength={6} /><button className="memory-secondary-button" disabled={!name.trim() || code.length !== 6 || busy} onClick={() => void enter(memoryJoinRoom(code, name))}>ODAYA KATIL</button></div>{error && <p className="memory-error">{error}</p>}</div></section>;
  const active = state.room.current_player_id === session.playerId; const finished = state.room.status === "finished";
  return <section className="classic-panel"><div className="classic-subbar"><button onClick={() => { window.localStorage.removeItem("gs_memory_session"); setSession(null); setState(null); }}>← Çıkış</button><span>ODA {state.room.code}</span></div>{state.room.status === "waiting" ? <div className="classic-setup"><h2>Oyuncular · {state.players.length}/{state.room.max_players}</h2><ol className="memory-player-list">{state.players.map((player) => <li key={player.id}>{player.name}{player.is_host ? " · HOST" : ""}</li>)}</ol>{state.players.find((player) => player.id === session.playerId)?.is_host && <button className="memory-primary-button" disabled={state.players.length < 2} onClick={() => void memoryStartRoom(session).then(() => refresh())}>OYUNU BAŞLAT</button>}<p className="memory-code">ODA KODU <strong>{state.room.code}</strong></p></div> : <><p className={`memory-turn ${active ? "your-turn" : ""}`}>{finished ? "🏆 HAFIZA ŞAMPİYONU" : active ? "SIRA SENDE" : `SIRA: ${state.players.find((p) => p.id === state.room.current_player_id)?.name ?? "..."}`}</p><div className={`classic-grid classic-grid-${state.room.card_count}`}>{state.cards.map((card) => <PlayerCard key={card.id} player={{ id: card.id, name: card.name ?? "Kapalı", image: card.image ?? "/players/missing.webp" }} open={card.state !== "hidden"} matched={card.state === "matched"} onClick={() => { if (active && !finished) void memoryFlipCard(session, card.id).then(() => refresh()); else if (!active) setError("Şu anda sıra sende değil."); }} />)}</div><ol className="memory-leaderboard">{[...state.players].sort((a,b) => b.score-a.score || b.matches-a.matches || a.wrong-b.wrong).map((player, index) => <li key={player.id}><b>{index + 1}.</b> {player.name}<strong>{player.score}</strong><small>{player.matches} eşleşme · {player.wrong} yanlış</small></li>)}</ol>{error && <p className="memory-error">{error}</p>}</>}</section>;
}

export function ClassicMemoryGame({ onBack }: { onBack: () => void }) {
  const [kind, setKind] = useState<"menu" | "solo" | "multi">("menu");
  if (kind === "solo") return <SoloClassic onBack={() => setKind("menu")} />;
  if (kind === "multi") return <MultiplayerClassic onBack={() => setKind("menu")} />;
  return <section className="classic-panel classic-mode-menu"><div className="classic-subbar"><button onClick={onBack}>← Ana Menü</button><span>KLASİK KART EŞLEŞTİRME</span></div><h1>KLASİK KART<br /><span>EŞLEŞTİRME</span></h1><p>Aynı Galatasaray futbolcusunun iki kartını bul.</p><div className="classic-mode-actions"><button onClick={() => setKind("solo")}><strong>TEK OYUNCU</strong><span>12–60 kart · kendi rekorun</span></button><button onClick={() => setKind("multi")}><strong>ÇOK OYUNCULU</strong><span>2–8 oyuncu · ortak tahta</span></button></div></section>;
}
