"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { getAudioManager } from "@/lib/audio/audioManager";
import { getMemoryRaceCardVisual } from "@/lib/memory-race/cardVisuals";
import { createBoard, MEMORY_RACE_LEVELS, MEMORY_RACE_MAX_PLAYERS, MEMORY_RACE_ROUNDS, type MemoryRaceLevel, type MemoryRaceSession } from "@/lib/memory-race-online/config";
import { createRoom, getState, hostStart, joinRoom, submit, tick, type MemoryRacePlayer, type MemoryRaceState } from "@/lib/memory-race-online/api";

const SESSION_KEY = "gs_memory_race_session";
type Screen = "home" | "setup" | "join" | "lobby" | "game" | "final";

function formatTime(value: number) { return `${Math.max(0, Math.floor(value / 60)).toString().padStart(2, "0")}:${(Math.max(0, value) % 60).toString().padStart(2, "0")}`; }
function sortPlayers(players: MemoryRacePlayer[]) { return [...players].sort((a, b) => b.score - a.score || b.correct - a.correct || a.wrong - b.wrong); }

export function MemoryRaceOnline() {
  const [screen, setScreen] = useState<Screen>("home");
  const [session, setSession] = useState<MemoryRaceSession | null>(null);
  const [state, setState] = useState<MemoryRaceState | null>(null);
  const [name, setName] = useState(""); const [code, setCode] = useState("");
  const [maxPlayers, setMaxPlayers] = useState(4); const [level, setLevel] = useState<MemoryRaceLevel>(1); const [rounds, setRounds] = useState(3);
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [selected, setSelected] = useState<number[]>([]); const [offset, setOffset] = useState(0); const [clientNow, setClientNow] = useState(0);
  const [soloBoard, setSoloBoard] = useState<ReturnType<typeof createBoard>>([]); const [soloOpen, setSoloOpen] = useState<number[]>([]); const [soloMatched, setSoloMatched] = useState<number[]>([]); const [soloScore, setSoloScore] = useState(0);
  const [lastRound, setLastRound] = useState(0);

  const refresh = useCallback(async (activeSession = session) => { if (!activeSession) return; try { const result = await getState(activeSession); setState(result.state); setOffset(result.serverOffsetMs); setError(""); setScreen(result.state.room.status === "finished" ? "final" : result.state.room.status === "waiting" ? "lobby" : "game"); } catch (e) { setError(e instanceof Error ? e.message : "Oda durumu alınamadı."); } }, [session]);
  useEffect(() => { try { const raw = window.localStorage.getItem(SESSION_KEY); if (raw) { const restored = JSON.parse(raw) as MemoryRaceSession; setSession(restored); void refresh(restored); } } catch { /* eski/bozuk oturum yok sayılır */ } }, [refresh]);
  useEffect(() => { if (!session) return; const timer = window.setInterval(() => { void refresh(); void tick(session).catch(() => undefined); }, 800); return () => window.clearInterval(timer); }, [session, refresh]);
  useEffect(() => { if (state?.room.current_round && state.room.current_round !== lastRound) { setSelected([]); setLastRound(state.room.current_round); } }, [state?.room.current_round, lastRound]);

  async function enter(request: Promise<{ room_id: string; player_id: string; token: string; code: string }>) { setBusy(true); setError(""); try { const result = await request; const next = { roomId: result.room_id, playerId: result.player_id, token: result.token, code: result.code }; window.localStorage.setItem(SESSION_KEY, JSON.stringify(next)); setSession(next); await refresh(next); } catch (e) { setError(e instanceof Error ? e.message : "Odaya bağlanılamadı."); } finally { setBusy(false); } }
  function startSolo() { setSoloBoard(createBoard(level)); setSoloOpen([]); setSoloMatched([]); setSoloScore(0); setScreen("game"); }
  function leave() { window.localStorage.removeItem(SESSION_KEY); setSession(null); setState(null); setScreen("home"); }
  useEffect(() => { const timer = window.setInterval(() => setClientNow(Date.now()), 250); setClientNow(Date.now()); return () => window.clearInterval(timer); }, []);
  const serverNow = clientNow + offset; const remaining = state?.room.ends_at && clientNow ? Math.ceil((Date.parse(state.room.ends_at) - serverNow) / 1000) : 0;
  const me = state?.players.find((player) => player.id === session?.playerId);
  const isHost = !!me?.is_host;

  if (screen === "home") return <PageShell><div className="race-hero"><Link href="/" className="race-back">← Ana Menü</Link><div className="race-logo">GS</div><p className="race-kicker">GALATASARAY · CANLI OYUN</p><h1>HAFIZA<br /><span>YARIŞI ONLINE</span></h1><p>Aynı hafıza parkurunda arkadaşlarınla canlı yarış.</p><div className="race-actions"><button onClick={() => setScreen("setup")}>TEK OYUNCU</button><button onClick={() => setScreen("setup")}>ODA OLUŞTUR</button><button className="race-secondary" onClick={() => setScreen("join")}>ODAYA KATIL</button></div></div></PageShell>;
  if (screen === "setup" && !session) return <PageShell><Setup title="Oyuncu ve seviye seç" name={name} setName={setName} level={level} setLevel={setLevel} maxPlayers={maxPlayers} setMaxPlayers={setMaxPlayers} rounds={rounds} setRounds={setRounds} onBack={() => setScreen("home")} onCreate={() => void enter(createRoom(name, maxPlayers, level, rounds))} onSolo={startSolo} busy={busy} error={error} /></PageShell>;
  if (screen === "join" && !session) return <PageShell><div className="race-panel"><button className="race-back" onClick={() => setScreen("home")}>← Geri</button><p className="race-kicker">ODA KODU</p><h2>Yarışa katıl</h2><input className="race-input" value={name} onChange={(e) => setName(e.target.value)} placeholder="Oyuncu adın" maxLength={24} /><input className="race-input" value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="6 karakterli oda kodu" maxLength={6} /><button className="race-primary" disabled={!name.trim() || code.length !== 6 || busy} onClick={() => void enter(joinRoom(code, name))}>ODAYA KATIL</button>{error && <p className="race-error">{error}</p>}</div></PageShell>;
  if (screen === "lobby" && state && session) return <PageShell><div className="race-panel"><p className="race-kicker">BEKLEME ODASI</p><h2>Oda {state.room.code}</h2><p className="race-muted">Oyuncular · {state.players.length}/{state.room.max_players}</p><div className="race-players">{state.players.map((player) => <div key={player.id} className={player.id === session.playerId ? "race-player mine" : "race-player"}>👤 {player.name}{player.is_host && <small> HOST</small>}</div>)}</div>{isHost ? <button className="race-primary" disabled={state.players.length < 2 || busy} onClick={() => void hostStart(session).then(() => refresh())}>OYUNU BAŞLAT</button> : <p className="race-muted">Oda sahibinin oyunu başlatması bekleniyor…</p>}<button className="race-link" onClick={leave}>Odadan çık</button>{error && <p className="race-error">{error}</p>}</div></PageShell>;
  if (screen === "game" && state && session) return <PageShell><OnlineBoard state={state} session={session} selected={selected} setSelected={setSelected} remaining={remaining} onSubmit={async (a, b) => { setBusy(true); try { await submit(session, a, b); if (b >= 0) { getAudioManager().playRevealEffect(true); window.setTimeout(() => setSelected([]), 1300); } await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Cevap gönderilemedi."); } finally { setBusy(false); } }} busy={busy} error={error} onLeave={leave} /></PageShell>;
  if (screen === "game" && soloBoard.length) return <SoloBoard board={soloBoard} open={soloOpen} matched={soloMatched} score={soloScore} onCard={(index) => { if (soloOpen.length >= 2 || soloMatched.includes(index) || soloOpen.includes(index)) return; const next = [...soloOpen, index]; setSoloOpen(next); if (next.length === 2) { const match = soloBoard[next[0]].pair === soloBoard[index].pair; window.setTimeout(() => { if (match) { setSoloMatched((v) => [...v, ...next]); setSoloScore((v) => v + 100); } setSoloOpen([]); }, match ? 260 : 720); } }} onBack={() => setScreen("home")} />;
  if (screen === "final" && state && session) return <PageShell><div className="race-panel"><p className="race-kicker">🏆 HAFIZA YARIŞI ŞAMPİYONU</p><h2>{sortPlayers(state.players)[0]?.name}</h2><Leaderboard players={state.players} me={session.playerId} final /><button className="race-primary" onClick={leave}>ANA MENÜ</button></div></PageShell>;
  return <PageShell><div className="race-panel"><p className="race-error">Oyun oturumu hazırlanıyor…</p></div></PageShell>;
}

function PageShell({ children }: { children: React.ReactNode }) { return <main className="memory-page race-page"><section className="memory-shell race-shell">{children}</section></main>; }
type SetupProps = { title: string; name: string; setName: (value: string) => void; level: MemoryRaceLevel; setLevel: (value: MemoryRaceLevel) => void; maxPlayers: number; setMaxPlayers: (value: number) => void; rounds: number; setRounds: (value: number) => void; onBack: () => void; onCreate: () => void; onSolo: () => void; busy: boolean; error: string };
function Setup({ title, name, setName, level, setLevel, maxPlayers, setMaxPlayers, rounds, setRounds, onBack, onCreate, onSolo, busy, error }: SetupProps) { return <div className="race-panel"><button className="race-back" onClick={onBack}>← Geri</button><p className="race-kicker">HAFIZA YARIŞI ONLINE</p><h2>{title}</h2><input className="race-input" value={name} onChange={(e) => setName(e.target.value)} placeholder="Oyuncu adın" maxLength={24} /><h3>Seviye</h3><div className="race-options">{Object.entries(MEMORY_RACE_LEVELS).map(([key, item]) => <button key={key} className={level === Number(key) ? "chosen" : ""} onClick={() => setLevel(Number(key) as MemoryRaceLevel)}>{item.label}<small>{item.cards} kart</small></button>)}</div><h3>Oyuncu sayısı</h3><div className="race-options">{MEMORY_RACE_MAX_PLAYERS.map((value) => <button key={value} className={maxPlayers === value ? "chosen" : ""} onClick={() => setMaxPlayers(value)}>{value}</button>)}</div><h3>Tur sayısı</h3><div className="race-options">{MEMORY_RACE_ROUNDS.map((value) => <button key={value} className={rounds === value ? "chosen" : ""} onClick={() => setRounds(value)}>{value}</button>)}</div><button className="race-primary" disabled={!name.trim() || busy} onClick={onCreate}>ODA OLUŞTUR</button><button className="race-secondary" disabled={!name.trim()} onClick={onSolo}>TEK OYUNCU BAŞLAT</button>{error && <p className="race-error">{error}</p>}</div>; }
type OnlineBoardProps = { state: MemoryRaceState; session: MemoryRaceSession; selected: number[]; setSelected: (value: number[]) => void; remaining: number; onSubmit: (first: number, second: number) => Promise<void>; busy: boolean; error: string; onLeave: () => void };
function OnlineBoard({ state, session, selected, setSelected, remaining, onSubmit, busy, error, onLeave }: OnlineBoardProps) { const level = MEMORY_RACE_LEVELS[state.room.level]; const cards = state.cards; return <div className="race-panel"><div className="race-board-head"><div><p className="race-kicker">TUR {state.room.current_round}/{state.room.round_count}</p><h2>{level.label}</h2></div><strong>{formatTime(remaining)}</strong></div><p className="race-muted">Kartları hatırla, iki kart seç. Her oyuncu kendi hamlesini yapar.</p><div className={`race-grid race-grid-${cards.length}`}>{cards.map((card) => <button key={card.index} className={`race-card ${card.matched ? "matched" : ""} ${selected.includes(card.index) ? "open" : ""}`} disabled={busy || card.matched} onClick={() => { const next = selected.length === 2 ? [card.index] : [...selected, card.index]; setSelected(next); void onSubmit(next[0], next.length === 2 ? next[1] : -1); }}><span className="race-card-inner"><span className="race-card-front">?</span><span className="race-card-back">{getMemoryRaceCardVisual(state.room.level, card.value)}</span></span></button>)}</div><Leaderboard players={state.players} me={session.playerId} /><button className="race-link" onClick={onLeave}>Oyundan çık</button>{error && <p className="race-error">{error}</p>}</div>; }
function Leaderboard({ players, me, final = false }: { players: MemoryRacePlayer[]; me: string; final?: boolean }) { return <div className={final ? "race-leaderboard final" : "race-leaderboard"}>{sortPlayers(players).map((player, index) => <div key={player.id} className={player.id === me ? "mine" : ""}><b>{index + 1}.</b><span>{player.name}{player.id === me && " · SEN"}</span><strong>{player.score}</strong><small>{player.correct} doğru · {player.wrong} yanlış</small></div>)}</div>; }
type SoloBoardProps = { board: ReturnType<typeof createBoard>; open: number[]; matched: number[]; score: number; onCard: (index: number) => void; onBack: () => void };
function SoloBoard({ board, open, matched, score, onCard, onBack }: SoloBoardProps) { return <PageShell><div className="race-panel"><button className="race-back" onClick={onBack}>← Ana Menü</button><div className="race-board-head"><div><p className="race-kicker">TEK OYUNCU</p><h2>HAFIZA YARIŞI</h2></div><strong>{score}</strong></div><div className={`race-grid race-grid-${board.length}`}>{board.map((card, index) => <button key={card.id} className={`race-card ${open.includes(index) || matched.includes(index) ? "open" : ""} ${matched.includes(index) ? "matched" : ""}`} onClick={() => onCard(index)}><span className="race-card-inner"><span className="race-card-front">?</span><span className="race-card-back">{open.includes(index) || matched.includes(index) ? card.value : "?"}</span></span></button>)}</div></div></PageShell>; }
